// Words the video model tends to misread in Cantonese, with Jyutping (粵拼).
// Mostly 多音字 and words where the Mandarin reading leaks in. One syllable per character.
export const CANTONESE_JYUTPING: Array<[string, string]> = [
  // Money and business
  ["生財", "saang1 coi4"],
  ["賺錢", "zaan6 cin2"],
  ["慳錢", "haan1 cin2"],
  ["蝕本", "sit6 bun2"],
  ["數錢", "sou2 cin2"],
  ["免費", "min5 fai3"],
  ["市況", "si5 fong3"],
  ["銀行", "ngan4 hong4"],
  ["行業", "hong4 jip6"],
  ["會計", "kui2 gai3"],
  ["投資", "tau4 zi1"],
  ["融資", "jung4 zi1"],
  ["股票", "gu2 piu3"],
  ["盈利", "jing4 lei6"],
  ["利潤", "lei6 jeon6"],
  ["稅務", "seoi3 mou6"],
  ["租金", "zou1 gam1"],
  ["物業", "mat6 jip6"],
  ["按揭", "on3 kit3"],
  ["供樓", "gung1 lau2"],
  ["儲蓄", "cyu5 cuk1"],
  ["營業額", "jing4 jip6 ngaak6"],
  ["客戶", "haak3 wu6"],
  ["品牌", "ban2 paai4"],
  ["銷售", "siu1 sau6"],
  ["促銷", "cuk1 siu1"],
  ["推廣", "teoi1 gwong2"],
  ["宣傳", "syun1 cyun4"],
  ["創業", "cong3 jip6"],
  ["供應", "gung1 jing3"],
  ["降價", "gong3 gaa3"],
  ["埋單", "maai4 daan1"],
  ["人工", "jan4 gung1"],
  ["老細", "lou5 sai3"],
  ["返工", "faan1 gung1"],
  ["放工", "fong3 gung1"],
  ["出差", "ceot1 caai1"],
  ["開會", "hoi1 wui2"],
  ["搵食", "wan2 sik6"],

  // Social media and content
  ["粉絲", "fan2 si1"],
  ["追蹤", "zeoi1 zung1"],
  ["訂閱", "deng6 jyut6"],
  ["直播", "zik6 bo3"],
  ["頻道", "pan4 dou6"],
  ["演算法", "jin2 syun3 faat3"],
  ["網絡", "mong5 lok3"],
  ["網上", "mong5 soeng6"],
  ["平台", "ping4 toi4"],
  ["內容", "noi6 jung4"],
  ["創作", "cong3 zok3"],
  ["互動", "wu6 dung6"],
  ["留言", "lau4 jin4"],
  ["分享", "fan1 hoeng2"],
  ["曝光", "bok6 gwong1"],
  ["收藏", "sau1 cong4"],
  ["相片", "soeng2 pin2"],
  ["技能", "gei6 nang4"],

  // 多音字: 行 / 重 / 長 / 好 / 會 / 樂 / 調 / 處
  ["行動", "hang4 dung6"],
  ["行為", "hang4 wai4"],
  ["行街", "haang4 gaai1"],
  ["重要", "zung6 jiu3"],
  ["重新", "cung4 san1"],
  ["重複", "cung4 fuk1"],
  ["長大", "zoeng2 daai6"],
  ["長期", "coeng4 kei4"],
  ["增長", "zang1 zoeng2"],
  ["成長", "sing4 zoeng2"],
  ["校長", "haau6 zoeng2"],
  ["好奇", "hou3 kei4"],
  ["愛好", "oi3 hou3"],
  ["好彩", "hou2 coi2"],
  ["機會", "gei1 wui6"],
  ["音樂", "jam1 ngok6"],
  ["樂觀", "lok6 gun1"],
  ["調查", "diu6 caa4"],
  ["調整", "tiu4 zing2"],
  ["空調", "hung1 tiu4"],
  ["處理", "cyu5 lei5"],
  ["好處", "hou2 cyu3"],

  // 多音字: 數 / 傳 / 教 / 參 / 差 / 覺 / 分 / 便 / 種 / 應 / 相 / 為 / 中 / 看 / 藏
  ["數據", "sou3 geoi3"],
  ["數字", "sou3 zi6"],
  ["計數", "gai3 sou3"],
  ["傳統", "cyun4 tung2"],
  ["自傳", "zi6 zyun6"],
  ["教育", "gaau3 juk6"],
  ["教書", "gaau3 syu1"],
  ["參加", "caam1 gaa1"],
  ["人參", "jan4 sam1"],
  ["參差", "caam1 ci1"],
  ["差不多", "caa1 bat1 do1"],
  ["了解", "liu5 gaai2"],
  ["覺得", "gok3 dak1"],
  ["睡覺", "seoi6 gaau3"],
  ["部分", "bou6 fan6"],
  ["背景", "bui3 ging2"],
  ["便宜", "pin4 ji4"],
  ["方便", "fong1 bin6"],
  ["便利店", "bin6 lei6 dim3"],
  ["種類", "zung2 leoi6"],
  ["種植", "zung3 zik6"],
  ["創傷", "cong1 soeng1"],
  ["應該", "jing1 goi1"],
  ["回應", "wui4 jing3"],
  ["相信", "soeng1 seon3"],
  ["首相", "sau2 soeng3"],
  ["為了", "wai6 liu5"],
  ["因為", "jan1 wai6"],
  ["作為", "zok3 wai4"],
  ["中獎", "zung3 zoeng2"],
  ["間中", "gaan3 zung1"],
  ["看守", "hon1 sau2"],
  ["角色", "gok3 sik1"],

  // Time words
  ["星期一", "sing1 kei4 jat1"],
  ["禮拜", "lai5 baai3"],
  ["下晝", "haa6 zau3"],
  ["而家", "ji4 gaa1"],
  ["今日", "gam1 jat6"],
  ["聽日", "ting1 jat6"],
  ["尋日", "cam4 jat6"],
  ["琴日", "kam4 jat6"],

  // Hong Kong colloquial words
  ["做嘢", "zou6 je5"],
  ["乜嘢", "mat1 je5"],
  ["點解", "dim2 gaai2"],
  ["唔該", "m4 goi1"],
  ["冇問題", "mou5 man6 tai4"],
  ["睇下", "tai2 haa5"],
  ["諗住", "nam2 zyu6"],
  ["傾偈", "king1 gai2"],
  ["搞掂", "gaau2 dim6"],
  ["鍾意", "zung1 ji3"],
  ["識得", "sik1 dak1"],
  ["一齊", "jat1 cai4"],
  ["咁樣", "gam2 joeng2"],
  ["呃人", "ak1 jan4"],
  ["靚仔", "leng3 zai2"],
];
