import type { CatalogStyleFields, CatalogStyleSpec } from "@/service/style/catalog-styles";

// Shared reel-safe lettering. `hand` names the lettering of that one style.
function lettering(hand: string): Pick<
  CatalogStyleFields,
  "letteringLayout" | "letteringLine1" | "letteringLine2" | "beatTitleLayout" | "reelLayout"
> {
  return {
    letteringLayout: `One short line in ${hand}, lower third, clear of the subject.`,
    letteringLine1: `${hand}, one line, high contrast.`,
    letteringLine2: "A smaller second line in the same hand when a second line exists.",
    beatTitleLayout: `A short title in ${hand} near the subject, not a paragraph.`,
    reelLayout: "Keep type inside the center safe area, away from the top and bottom edges.",
  };
}

function style(
  id: CatalogStyleSpec["id"],
  fields: Omit<CatalogStyleFields, "letteringLayout" | "letteringLine1" | "letteringLine2" | "beatTitleLayout" | "reelLayout">,
  hand: string,
): CatalogStyleSpec {
  return { id, fields: { ...fields, ...lettering(hand) } };
}

// Sixteen art-history looks from the speedrun reel. Appended after the original catalog.
export const ART_HISTORY_STYLES: CatalogStyleSpec[] = [
  style("cave-painting", {
    name: "Cave painting",
    description: "赭石岩壁上的手印、動物與簡筆人物。",
    canvas: "rough ochre cave wall with soot stains and sprayed handprints",
    canvasColor: "#c4a574",
    look: "prehistoric cave painting: uneven mineral pigment, stick figures and animals in profile, no perspective",
    palette: "ochre, charcoal, rust red, and bone white on a warm rock wall",
    typography: "scratched charcoal capitals, short and uneven",
    motion: "figures shuffle in profile; pigment blooms onto the rock; the wall stays fixed",
    negatives: "photoreal faces, clean vector, perspective rooms, neon, pixels, glossy 3D",
  }, "scratched charcoal capitals"),
  style("egyptian-wall", {
    name: "Egyptian wall painting",
    description: "莎草紙色底、側面人像與象形文字邊框。",
    canvas: "flat papyrus-coloured wall with a band of hieroglyphs along the top",
    canvasColor: "#e7d7a8",
    look: "ancient Egyptian wall painting: composite profile view, flat colour, heavy outlines, figures on a ground line",
    palette: "papyrus cream, turquoise, lapis blue, gold, and terracotta",
    typography: "geometric block capitals, evenly spaced, like carved signs",
    motion: "figures slide along the ground line; colour fills in flat bands",
    negatives: "perspective, shading, photoreal skin, pixels, watercolor bloom, 3D render",
  }, "geometric block capitals"),
  style("attic-black-figure", {
    name: "Attic black-figure",
    description: "橙紅陶瓶上的黑繪剪影與幾何邊飾。",
    canvas: "orange-red pottery surface with a black Greek-key border",
    canvasColor: "#c4512c",
    look: "Attic black-figure vase painting: black silhouettes on orange clay, incised details, profile figures, meander border",
    palette: "terracotta orange, black, and a little white for incised highlights",
    typography: "black block capitals on the orange ground, short, inside the border",
    motion: "silhouettes step in profile across the vase; the border stays still",
    negatives: "full-colour painting, perspective interior, photoreal, pixels, watercolor, 3D",
  }, "black block capitals"),
  style("roman-mosaic", {
    name: "Roman mosaic",
    description: "小石磚拼出的人物、邊框與銘文。",
    canvas: "a wall of small square tesserae with a decorative mosaic border",
    canvasColor: "#7a1f2b",
    look: "Roman mosaic: every shape built from visible square tiles, hard edges, ornamental border, no brush strokes",
    palette: "deep red, cream, black, gold, and a little sea blue",
    typography: "tile-built Roman capitals, one short line, as if set in stone",
    motion: "tiles pop into place to form the figure; the border is already complete",
    negatives: "smooth paint, photoreal skin, chalk, watercolor, 3D gloss, vector gradients",
  }, "tile-built Roman capitals"),
  style("gothic-illumination", {
    name: "Gothic illumination",
    description: "金箔底、花邊框與手抄本裝飾首字。",
    canvas: "gold-leaf manuscript page with a painted vine border",
    canvasColor: "#c6a15b",
    look: "Gothic illuminated manuscript: flat gold ground, jewel colours, patterned robes, a large decorated initial",
    palette: "gold, ultramarine, vermilion, and parchment cream",
    typography: "blackletter title with one decorated initial, short and readable",
    motion: "the initial draws itself, gold fills the ground, figures settle into the frame",
    negatives: "photoreal, pixels, modern sans, chalkboard, 3D, impressionist brushwork",
  }, "blackletter"),
  style("high-renaissance", {
    name: "High Renaissance",
    description: "柔和光影、透視窗景與靜物的古典油畫。",
    canvas: "a quiet interior with a window, tiled floor, and warm directional light",
    canvasColor: "#6e5848",
    look: "High Renaissance oil painting: soft chiaroscuro, accurate perspective, calm posed figures, glazed colour, no cartoon outlines",
    palette: "warm brown, deep green, wine red, and pale sky through the window",
    typography: "small classical serif capitals, restrained, like an inscription",
    motion: "light shifts slowly; figures barely move; the camera holds",
    negatives: "flat vector, pixels, thick outlines, neon, chalkboard, clay, manga speed lines",
  }, "classical serif capitals"),
  style("ukiyo-e", {
    name: "Ukiyo-e",
    description: "浮世繪木版畫：平塗色塊、黑線與和紙。",
    canvas: "warm washi paper with a thin black keyline border",
    canvasColor: "#f3e6c4",
    look: "Japanese ukiyo-e woodblock print: flat colour areas, crisp black keylines, patterned textiles, a distant landscape motif",
    palette: "indigo, vermilion, ochre, black, and paper cream",
    typography: "bold woodblock-printed capitals, black on the paper, short",
    motion: "colour blocks stamp in one after another; figures slide in profile",
    negatives: "photoreal, oil impasto, pixels, 3D, chalk, watercolor bloom, Western shading",
  }, "woodblock-printed capitals"),
  style("impressionism", {
    name: "Impressionism",
    description: "可見筆觸、戶外光與淡紫陰影的印象派。",
    canvas: "sunlit interior opening onto a bright garden",
    canvasColor: "#e4d2be",
    look: "Impressionist painting: broken visible brushstrokes, outdoor light, soft edges, no ink outlines",
    palette: "lilac, sky blue, sunflower yellow, leaf green, and warm white",
    typography: "loose painted letters, slightly soft, still readable, one short line",
    motion: "light flickers; strokes shimmer; figures shift gently",
    negatives: "hard outlines, flat vector, pixels, photoreal photo, chalkboard, clay, black comic ink",
  }, "loose painted letters"),
  style("post-impressionism", {
    name: "Post-Impressionism",
    description: "旋渦筆觸、高彩與厚塗的後印象派。",
    canvas: "an interior wall covered in directional swirling strokes",
    canvasColor: "#2f5f9a",
    look: "Post-Impressionist painting: thick directional strokes, heightened colour, visible impasto, expressive not photographic",
    palette: "cobalt blue, chrome yellow, emerald, and orange",
    typography: "painted letters built from the same thick strokes, short and high contrast",
    motion: "strokes swirl into place; colour pulses; the pose stays readable",
    negatives: "flat vector, photoreal, pixels, clean outlines, chalkboard, 3D gloss",
  }, "thick painted letters"),
  style("art-nouveau", {
    name: "Art Nouveau",
    description: "新藝術海報：植物曲線、平面色與裝飾框。",
    canvas: "a poster with a whiplash floral border and a stained-glass window",
    canvasColor: "#d5c6a4",
    look: "Art Nouveau poster: sinuous plant lines, flat muted colour, decorative frame, elegant profile figures",
    palette: "sage, blush, cream, black line, and a little gold",
    typography: "tall elegant poster lettering, high contrast, one short line inside the frame",
    motion: "vines draw themselves around the frame; colour flats fill in",
    negatives: "photoreal, pixels, harsh geometry, chalk, 3D, grunge texture",
  }, "tall poster lettering"),
  style("cubism", {
    name: "Cubism",
    description: "幾何切面、多角度同時出現的立體派。",
    canvas: "a shallow fractured space of overlapping planes",
    canvasColor: "#cbbba6",
    look: "Cubist painting: the subject broken into flat geometric facets, several viewpoints at once, no single vanishing point",
    palette: "taupe, ochre, slate blue, and a little wood brown",
    typography: "stenciled block letters on one facet, short",
    motion: "planes slide and reassemble; the subject stays recognizable",
    negatives: "photoreal, cute flat illustration, pixels, watercolor, one-point perspective room, chalk",
  }, "stenciled block letters"),
  style("bauhaus", {
    name: "Bauhaus",
    description: "包浩斯：原色、幾何、網格與無襯線。",
    canvas: "off-white poster with a strict grid and primary-colour blocks",
    canvasColor: "#f4f1ea",
    look: "Bauhaus graphic design: circles, squares, and bars, asymmetric balance, no texture",
    palette: "red, yellow, blue, black, and off-white",
    typography: "bold geometric sans, aligned to the grid, short",
    motion: "shapes snap to the grid, slide on rails, and scale; no organic wobble",
    negatives: "painterly strokes, photoreal, pixels, decoration, script fonts, chalk, clay",
  }, "bold geometric sans"),
  style("pop-art", {
    name: "Pop art",
    description: "普普藝術：網點、粗黑邊與高彩平塗。",
    canvas: "a flat comic field of Ben-Day dots",
    canvasColor: "#f2d63b",
    look: "Pop art: thick black outlines, flat unmodulated colour, Ben-Day dots, comic close-up energy",
    palette: "cyan, magenta, yellow, black, and white",
    typography: "bold comic display letters in a yellow box, all caps, one short line",
    motion: "panels slam in; dots stamp on; colour holds flat",
    negatives: "painterly realism, soft watercolor, chalk, 3D render, muted palette, thin lines",
  }, "bold comic capitals"),
  style("eight-bit", {
    name: "8-bit",
    description: "8-bit 遊戲畫面：大方塊、有限色與像素字。",
    canvas: "a chunky pixel scene with a limited console palette",
    canvasColor: "#241b4a",
    look: "8-bit pixel art: large visible square pixels, no anti-aliasing, limited colours per sprite, side-view game scene",
    palette: "a small set of navy, red, cream, leaf green, and gold",
    typography: "pixel-font capitals, one short line, aligned to the pixel grid",
    motion: "sprites step in whole pixels; no smooth blur, no sub-pixel motion",
    negatives: "anti-aliased vectors, photoreal, paint strokes, high-resolution detail, 3D gloss, watercolor",
  }, "pixel-font capitals"),
  style("ray-traced", {
    name: "Ray-traced CGI",
    description: "早期光線追蹤：金屬球、棋盤地與漸層天空。",
    canvas: "a reflective studio with a checker floor and a gradient sky",
    canvasColor: "#147a86",
    look: "early ray-traced CGI: reflective spheres, checker floor, chrome highlights, smooth gradients, no brush marks",
    palette: "teal, chrome silver, a hot pink accent, and a sunset gradient",
    typography: "shiny beveled letters, short, sitting in the scene",
    motion: "reflections slide as the camera trucks slowly; objects glide",
    negatives: "paint, pixels, chalk, paper texture, flat vector, hand-drawn outlines, clay",
  }, "shiny beveled letters"),
  style("flat-illustration", {
    name: "Flat illustration",
    description: "無外框扁平插畫、色塊背景與室內植物。",
    canvas: "a cream field of soft overlapping colour blobs",
    canvasColor: "#f6f1e8",
    look: "modern flat illustration: solid shapes, almost no outlines, simple geometric people, houseplants and a window",
    palette: "cream, coral, leaf green, lilac, and a sunny yellow accent",
    typography: "rounded geometric sans, bold, one short line, high contrast",
    motion: "shapes slide and pop on; blobs ease in; no texture crawl",
    negatives: "comic outlines, photoreal, pixels, paint strokes, chalk, 3D gloss, mosaic tiles",
  }, "rounded geometric sans"),
];
