import type { CatalogStyleFields, CatalogStyleSpec } from "@/service/style/catalog-styles";

// Six Reels looks: cream poster, highlighter notes, grid 3D icons,
// dark proof poster, number rings, and a wireframe sports breakdown.
function style(
  id: CatalogStyleSpec["id"],
  fields: CatalogStyleFields,
): CatalogStyleSpec {
  return { id, fields };
}

export const REEL_STYLES: CatalogStyleSpec[] = [
  style("cream-poster", {
    name: "Cream editorial poster",
    description: "奶油紙底、超大黑字與鏽橙重點，下面一排線稿圖示卡。",
    canvas: "warm cream paper, flat, with a wide empty margin",
    canvasColor: "#f6efe6",
    look: "editorial social poster on cream paper. Giant black display type fills the upper half. One word is rust-orange italic serif. Along the bottom, a row of rounded cream cards holds rust line icons: a person pointing, and a light bulb. The bulb card is labeled IDEA. Small tracked caps sit above the headline with a rust dot. No photographed people.",
    palette: "cream paper, near-black ink, and one rust-orange accent",
    typography: "huge high-contrast display sans, with a single rust italic serif word",
    motion: "icon cards slide in from the right; the accent word fades up; the paper stays still",
    negatives: "photoreal faces, clay, chalk, watercolor, pixels, comic halftone, dark background, app chrome, like buttons",
    letteringLayout: "IDEA is the giant black headline in the upper half, clear of the icon cards.",
    letteringLine1: "Huge black display sans, one line, reading IDEA.",
    letteringLine2: "A smaller tracked sans line under the headline when a second line exists.",
    beatTitleLayout: "A short cream-poster headline, not a caption bar.",
    reelLayout: "Keep the headline and icon row inside the center, away from the top and bottom edges.",
  }),
  style("highlighter-notes", {
    name: "Highlighter notes",
    description: "白紙上的馬克筆手寫，黃綠粉螢光筆畫出重點。",
    canvas: "plain white notebook paper with faint ruled lines",
    canvasColor: "#f7f4ee",
    look: "adult study notes in marker. Uneven handwritten lines. Neon highlighter bands in yellow, green, and pink sit behind key words. A simple marker person points at a hand-drawn light bulb. The bulb label IDEA sits on a yellow highlighter stroke.",
    palette: "paper white, marker black, highlighter yellow, green, and pink",
    typography: "handwritten marker capitals, slightly messy, one word on a highlighter band",
    motion: "a highlighter swipes across a word; marker lines draw themselves on",
    negatives: "crayon texture, children's book, chalkboard, 3D render, photoreal, watercolor bloom, pixel art, glossy vector",
    letteringLayout: "Handwritten IDEA sits on a yellow highlighter band beside the bulb.",
    letteringLine1: "Marker capitals, one line, reading IDEA, on a highlighter stroke.",
    letteringLine2: "A smaller marker line under it when a second line exists.",
    beatTitleLayout: "A highlighted handwritten title, not a printed caption.",
    reelLayout: "Notes stay on the page, clear of the top and bottom edges.",
  }),
  style("grid-icons", {
    name: "Grid 3D icons",
    description: "方格紙上的充氣立體字、白色圖示卡與一道橘色筆刷。",
    canvas: "pale graph paper with a fine square grid",
    canvasColor: "#f3f1ea",
    look: "inflated plastic 3D letters and chunky 3D icons on graph paper. White rounded cards float in a row. One thick orange paint slash sits behind the title. Soft studio shadows. The person and the light bulb are plastic 3D icons on the cards, not clay figures in a room. The bulb card reads IDEA.",
    palette: "graph-paper cream, white cards, an orange slash, and primary plastic colours on the icons",
    typography: "huge inflated 3D sans with a soft highlight, short",
    motion: "cards pop forward; the 3D letters settle with a small bounce; the grid stays fixed",
    negatives: "clay fingerprints, photoreal skin, chalk, watercolor, pixels, dark void, chrome spheres",
    letteringLayout: "IDEA is the inflated 3D title above the icon cards.",
    letteringLine1: "Inflated 3D sans, one short line, reading IDEA.",
    letteringLine2: "A smaller flat sans line under the 3D title when a second line exists.",
    beatTitleLayout: "A short 3D title on the grid, not a paragraph.",
    reelLayout: "Title and cards stay inside the grid, away from the top and bottom edges.",
  }),
  style("proof-poster", {
    name: "Dark proof poster",
    description: "黑底、撕邊數據圖與超大白色標題。",
    canvas: "a solid black field",
    canvasColor: "#111111",
    look: "dark proof poster. A torn-paper plate holds a simple light chart. A huge white grotesque headline fills the lower half and reads IDEA. Two thin white line icons, a pointing person and a bulb, sit beside the plate. No 3D volumes and no science diagram.",
    palette: "black, white, and one violet accent on the chart",
    typography: "extra-bold grotesque sans, white, tight leading",
    motion: "the torn plate slides in; the headline snaps on; the black field stays still",
    negatives: "navy science diagram, glowing 3D volumes, chalk, clay, watercolor, cute mascot, daylight scene",
    letteringLayout: "IDEA is the huge white headline in the lower half, clear of the torn chart.",
    letteringLine1: "Extra-bold white grotesque sans, one line, reading IDEA.",
    letteringLine2: "A smaller white line under the headline when a second line exists.",
    beatTitleLayout: "A short white poster headline, not a thin diagram label.",
    reelLayout: "Headline and torn plate stay inside the frame, away from the top and bottom edges.",
  }),
  style("data-ring", {
    name: "Data ring",
    description: "深色同心圓、一圈數字，中央一道半透明大字。",
    canvas: "a near-black field of faint concentric circles",
    canvasColor: "#140e0c",
    look: "flat kinetic data mandala. White and rust digits sit on concentric rings. One huge translucent condensed phrase crosses the center and reads IDEA. No solid character and no 3D object; a tiny tick mark can stand where a person would point.",
    palette: "near-black, warm white, rust orange, and muted gray",
    typography: "condensed sans for the giant center phrase, tabular digits on the rings",
    motion: "rings rotate slowly in opposite directions; digits tick; the center phrase stays locked",
    negatives: "cute character, daylight, clay, chalk, watercolor, photoreal faces, science 3D volumes, game city",
    letteringLayout: "IDEA is the huge translucent phrase across the center of the rings.",
    letteringLine1: "Condensed sans, one line, warm white, reading IDEA.",
    letteringLine2: "A smaller muted line under the phrase when a second line exists.",
    beatTitleLayout: "The center phrase is the title, not a caption bar.",
    reelLayout: "The phrase stays inside the rings, clear of the top and bottom edges.",
  }),
  style("wireframe-breakdown", {
    name: "Wireframe breakdown",
    description: "去飽和場地上的青色線框人，上方疊分解標題。",
    canvas: "a daylight sports court, slightly desaturated, seen from the side",
    canvasColor: "#8d97a3",
    look: "sports analysis overlay on a photographic court. A glowing cyan wireframe mannequin points at a wireframe light bulb. Stacked athletic type at the top: small tracked caps, a huge white word, one lime word. The bulb callout reads IDEA. Checkpoint dots sit on the wireframe.",
    palette: "desaturated court gray, cyan wireframe, white type, and a lime accent",
    typography: "condensed athletic sans, white and lime, stacked, short",
    motion: "the wireframe holds the pose; the camera pushes in slowly; a checkpoint pulse travels along the wireframe",
    negatives: "cartoon mascot, clay, chalk, flat vector poster, pixel art, photoreal skin with no wireframe",
    letteringLayout: "IDEA is the huge white word in the stacked title at the top.",
    letteringLine1: "Condensed athletic sans, white, one line, reading IDEA.",
    letteringLine2: "A lime second line under it when a second line exists.",
    beatTitleLayout: "A stacked sports title above the figure, not a paragraph.",
    reelLayout: "The title stack stays in the upper safe band, clear of the top edge.",
  }),
];
